\pset pager off
DROP SCHEMA IF EXISTS public CASCADE;
DROP SCHEMA IF EXISTS garbage CASCADE;
DROP SCHEMA IF EXISTS source CASCADE;

CREATE SCHEMA public;
CREATE SCHEMA garbage;
CREATE SCHEMA source;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
